global:
  sysdig:
    accessKey: ${sysdigAccessKey}                  # Sysdig Agent Access Key
    region: ${sysdigRegion}
  kspm:
    deploy: true
  clusterConfig:
    name: ${sysdigClusterName}
agent:
  sysdig:
    settings:
      collector_port: 6443
nodeAnalyzer:
  nodeAnalyzer:
    benchmarkRunner:
      deploy: false
  secure:
    vulnerabilityManagement:
      newEngineOnly: true
